=== ShapeChange/ShapeChange/shapechange-app/src/integrationtests/sch/oclOnCodelistTypedProperty/test_instance_documents/testOclOnCodeListTypedProperty.xsd
<?xml version="1.0" encoding="UTF-8"?><schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:cliso="http://example.org/shapechange/sch/oclOnCodelistTypedProperty/iso19139" xmlns:ex="http://example.org/shapechange/sch/codelistCheck" xmlns:gml="http://www.opengis.net/gml/3.2" elementFormDefault="qualified" targetNamespace="http://example.org/shapechange/sch/codelistCheck" version="1">
  <import namespace="http://example.org/shapechange/sch/oclOnCodelistTypedProperty/iso19139" schemaLocation="./codeListIso19139.xsd"/>
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd"/>
  <!--XML Schema document created by ShapeChange - http://shapechange.net/-->
  <element name="DataType" substitutionGroup="gml:AbstractObject" type="ex:DataTypeType"/>
  <complexType name="DataTypeType">
    <sequence>
      <element name="att1iso" type="cliso:CodeListIso19139_PropertyType"/>
      <element maxOccurs="unbounded" name="att2iso" type="cliso:CodeListIso19139_PropertyType"/>
      <element name="att3Gml32" nillable="true">
        <complexType>
          <simpleContent>
            <extension base="gml:CodeType">
              <attribute name="nilReason" type="gml:NilReasonType"/>
            </extension>
          </simpleContent>
        </complexType>
      </element>
      <element maxOccurs="unbounded" name="att4Gml32" nillable="true">
        <complexType>
          <simpleContent>
            <extension base="gml:CodeType">
              <attribute name="nilReason" type="gml:NilReasonType"/>
            </extension>
          </simpleContent>
        </complexType>
      </element>
      <element name="att5Gml33" nillable="true">
        <complexType>
          <simpleContent>
            <extension base="gml:CodeType">
              <attribute name="nilReason" type="gml:NilReasonType"/>
            </extension>
          </simpleContent>
        </complexType>
      </element>
      <element maxOccurs="unbounded" name="att6Gml33" nillable="true">
        <complexType>
          <simpleContent>
            <extension base="gml:CodeType">
              <attribute name="nilReason" type="gml:NilReasonType"/>
            </extension>
          </simpleContent>
        </complexType>
      </element>
    </sequence>
  </complexType>
  <complexType name="DataTypePropertyType">
    <sequence>
      <element ref="ex:DataType"/>
    </sequence>
  </complexType>
  <element name="FeatureType" substitutionGroup="gml:AbstractFeature" type="ex:FeatureTypeType"/>
  <complexType name="FeatureTypeType">
    <complexContent>
      <extension base="gml:AbstractFeatureType">
        <sequence>
          <element name="attribute1iso" type="cliso:CodeListIso19139_PropertyType"/>
          <element maxOccurs="unbounded" name="attribute2iso" type="cliso:CodeListIso19139_PropertyType"/>
          <element name="attribute3Gml32" nillable="true">
            <complexType>
              <simpleContent>
                <extension base="gml:CodeType">
                  <attribute name="nilReason" type="gml:NilReasonType"/>
                </extension>
              </simpleContent>
            </complexType>
          </element>
          <element maxOccurs="unbounded" name="attribute4Gml32" nillable="true">
            <complexType>
              <simpleContent>
                <extension base="gml:CodeType">
                  <attribute name="nilReason" type="gml:NilReasonType"/>
                </extension>
              </simpleContent>
            </complexType>
          </element>
          <element name="attribute5Gml33" nillable="true">
            <complexType>
              <simpleContent>
                <extension base="gml:CodeType">
                  <attribute name="nilReason" type="gml:NilReasonType"/>
                </extension>
              </simpleContent>
            </complexType>
          </element>
          <element maxOccurs="unbounded" name="attribute6Gml33" nillable="true">
            <complexType>
              <simpleContent>
                <extension base="gml:CodeType">
                  <attribute name="nilReason" type="gml:NilReasonType"/>
                </extension>
              </simpleContent>
            </complexType>
          </element>
          <element name="dt" type="ex:DataTypePropertyType"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
  <complexType name="FeatureTypePropertyType">
    <sequence minOccurs="0">
      <element ref="ex:FeatureType"/>
    </sequence>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
  </complexType>
</schema>

=== ShapeChange/ShapeChange/src/test/resources/sch/oclOnCodelistTypedProperty/test_instance_documents/instance1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ex:FeatureType xmlns:xlink="http://www.w3.org/1999/xlink"
 xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:gco="http://www.isotc211.org/2005/gco"
 xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gts="http://www.isotc211.org/2005/gts"
 xmlns:gss="http://www.isotc211.org/2005/gss" xmlns:gsr="http://www.isotc211.org/2005/gsr"
 xmlns:clisox="http://example.org/shapechange/sch/oclOnCodelistTypedProperty/iso19139"
 xmlns:gmx="http://www.isotc211.org/2005/gmx"
 xmlns:ex="http://example.org/shapechange/sch/codelistCheck"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://example.org/shapechange/sch/codelistCheck ./testOclOnCodeListTypedProperty.xsd"
 gml:id="ID000">
 <ex:attribute1iso>
  <clisox:CodeListIso19139 codeList="file:/C:/TMP/CodeListIso19139.xml" codeListValue="code1"/>
 </ex:attribute1iso>
 <ex:attribute2iso>
  <clisox:CodeListIso19139 codeList="file:/C:/TMP/CodeListIso19139.xml" codeListValue="code2"/>
 </ex:attribute2iso>
 <ex:attribute2iso>
  <clisox:CodeListIso19139 codeList="file:/C:/TMP/CodeListIso19139.xml" codeListValue="code2"/>
 </ex:attribute2iso>
 <ex:attribute2iso gco:nilReason="missing"/>
 <ex:attribute3Gml32 codeSpace="file:/C:/TMP/CodeListGml32.xml">codeA</ex:attribute3Gml32>
 <ex:attribute4Gml32>codeB</ex:attribute4Gml32>
 <ex:attribute4Gml32 codeSpace="file:/C:/TMP/CodeListGml32.xml">codeB</ex:attribute4Gml32>
 <ex:attribute4Gml32 xsi:nil="true" nilReason="inapplicable"/>
 <ex:attribute5Gml33 codeSpace="file:/C:/TMP/CodeListGml33.xml">codeX</ex:attribute5Gml33>
 <ex:attribute6Gml33 codeSpace="file:/C:/TMP/CodeListGml33.xml">codeY</ex:attribute6Gml33>
  <ex:attribute6Gml33 codeSpace="file:/C:/TMP/CodeListGml33.xml">codeY</ex:attribute6Gml33>
 <ex:attribute6Gml33 xsi:nil="true" nilReason="withheld"/>
 <ex:dt>
  <ex:DataType>
   <ex:att1iso>
    <clisox:CodeListIso19139 codeList="file:/C:/TMP/CodeListIso19139.xml" codeListValue="code1"/>
   </ex:att1iso>
   <ex:att2iso>
    <clisox:CodeListIso19139 codeList="file:/C:/TMP/CodeListIso19139.xml" codeListValue="code2"/>
   </ex:att2iso>
   <ex:att2iso>
    <clisox:CodeListIso19139 codeList="file:/C:/TMP/CodeListIso19139.xml" codeListValue="code2"/>
   </ex:att2iso>
   <ex:att2iso gco:nilReason="missing"/>
   <ex:att3Gml32 codeSpace="file:/C:/TMP/CodeListGml32.xml">codeA</ex:att3Gml32>
   <ex:att4Gml32>codeB</ex:att4Gml32>
   <ex:att4Gml32 codeSpace="file:/C:/TMP/CodeListGml32.xml">codeB</ex:att4Gml32>
   <ex:att4Gml32 xsi:nil="true" nilReason="inapplicable"/>
   <ex:att5Gml33 codeSpace="file:/C:/TMP/CodeListGml33.xml">codeX</ex:att5Gml33>
   <ex:att6Gml33 codeSpace="file:/C:/TMP/CodeListGml33.xml">codeY</ex:att6Gml33>
   <ex:att6Gml33 codeSpace="file:/C:/TMP/CodeListGml33.xml">codeY</ex:att6Gml33>
   <ex:att6Gml33 xsi:nil="true" nilReason="withheld"/>
  </ex:DataType>
 </ex:dt>
</ex:FeatureType>
